name: Deploy Next.js app to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your deployment branch if necessary

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'  # Adjust the Node.js version if necessary

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Ensure this matches your build script
        env:
          NEXT_PUBLIC_apiKey: ${{ secrets.NEXT_PUBLIC_apiKey }}
          NEXT_PUBLIC_authDomain: ${{ secrets.NEXT_PUBLIC_authDomain }}
          NEXT_PUBLIC_projectId: ${{ secrets.NEXT_PUBLIC_projectId }}
          NEXT_PUBLIC_storageBucket: ${{ secrets.NEXT_PUBLIC_storageBucket }}
          NEXT_PUBLIC_messagingSenderId: ${{ secrets.NEXT_PUBLIC_messagingSenderId }}
          NEXT_PUBLIC_appId: ${{ secrets.NEXT_PUBLIC_appId }}
          NEXT_PUBLIC_measurementId: ${{ secrets.NEXT_PUBLIC_measurementId}}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # Ensure this matches your export directory
